### ISSUE TITLE
Update workflows for this module: tests, checks, dependencies and create release

### ISSUE THREAD

**Issue by obervinov** [obervinov/telegram-package#6]
- [x] Bump the templates of workflow to [v1.0.4](https://github.com/obervinov/_templates/releases/tag/v1.0.4)
- [x] Remove [this](https://github.com/obervinov/_templates/releases/tag/v1.0.4) rule to run _Tests and Checks_ in main branch 
- [x] Replace the old tasks with these in _Tests and Checks_ (added verify package and verify changelog)
```yml
jobs:
  pylint:
    uses: obervinov/_templates/.github/workflows/test.pylint.yml@v1.0.4
  verify-package:
    uses: obervinov/_templates/.github/workflows/verify.package.yml@v1.0.4
  verify-changelog:
    uses: obervinov/_templates/.github/workflows/verify.changelog.yml@v1.0.4
  pytest:
    uses: obervinov/_templates/.github/workflows/test.pytest-with-vault.yml@v1.0.4
```
- [x] Completely replace the contents of the _Create Release_ workflow with this body
```yml
name: Create GitHub Release

on:
  workflow_run:
    workflows: ["Tests and Checks"]
    branches: [main]
    types: 
      - completed
  push:
    branches: [main]
    paths: ['users/**']

jobs:
  create-release:
    uses: obervinov/_templates/.github/workflows/create.release.yml@v1.0.4
```
